$ErrorActionPreference='Stop';$r4=Split-Path -Parent $PSScriptRoot;$b=Join-Path $r4 '03_extraction\qa\repair\R4_2E_B1';$input=@(Import-Csv (Join-Path $b 'R4_2E_B1_BLIND_SUBSTANTIVE_REVIEW_INPUT.csv')|Where-Object BATCH_ID -eq 'B1-02'|Sort-Object ORDER_IN_BATCH);$manifest=Import-Csv (Join-Path $b 'R4_2E_B1_BATCH_MANIFEST.csv');if($input.Count-ne 36){throw 'B1-02 count'}
# ID|defect|anchor|actor|action|object|counterpart|recipient|relation|proposed actor|proposed action|proposed counterpart|proposed recipient|individual route|template status|generalizability|note
$data=@'
EXT-000202|YES|HIGH|YES|NO|NO|NO|NO|NEITHER|The Commission|shall have the right to participate|NONE_EXPLICIT|NONE_EXPLICIT|HUMAN_ADJUDICATION_REQUIRED|N/A|N/A|The row fuses three Article 68 propositions and promotes a later Commission relation.
EXT-000339|YES|HIGH|NO|YES|YES|N/A|N/A|NEITHER|NO_EXPLICIT_ACTOR|should be assisted|NONE_EXPLICIT|NONE_EXPLICIT|HUMAN_ADJUDICATION_REQUIRED|N/A|N/A|The Board is beneficiary of a passive proposition, not its expressed actor.
EXT-000455|YES|MEDIUM|YES|NO|NO|NO|NO|NEITHER|The Board|should issue guidelines|NONE_EXPLICIT|NONE_EXPLICIT|N/A|REQUIRES_MORE_REPRESENTATIVES|LOW|The discourse adverb replaces the modal predicate and the processing phrase is not relational.
EXT-000004|NO|HIGH|YES|YES|YES|N/A|N/A|NEITHER|The controller|shall facilitate|NONE_EXPLICIT|NONE_EXPLICIT|N/A|REJECTED|NONE|The Article 12 matrix proposition is retained.
EXT-000023|YES|HIGH|NO|NO|NO|NO|NO|NEITHER|The data subject; the controller|shall have the right to obtain; shall have the obligation to erase|NONE_EXPLICIT|NONE_EXPLICIT|N/A|REQUIRES_MORE_REPRESENTATIVES|LOW|The row crosses the entitlement and controller obligation propositions.
EXT-000026|PARTIALLY|HIGH|YES|NO|NO|UNCERTAIN|UNCERTAIN|UNCERTAIN|The data subject|shall have the right to receive and transmit|UNCERTAIN|UNCERTAIN|N/A|REQUIRES_MORE_REPRESENTATIVES|LOW|The deontic construction and coordinated data-portability predicates are incomplete.
EXT-000046|YES|HIGH|YES|NO|YES|N/A|NO|RECIPIENT_ONLY|the processor|shall inform|NONE_EXPLICIT|the controller|N/A|VALIDATED_WITH_CONDITIONS|CONDITIONAL|The source uses inform and names the controller as recipient.
EXT-000049|YES|HIGH|YES|YES|YES|NO|NO|RECIPIENT_ONLY|the processor|shall immediately inform|NONE_EXPLICIT|the controller|N/A|VALIDATED_WITH_CONDITIONS|CONDITIONAL|Fields imported from the preceding audit proposition must not replace the point h information proposition.
EXT-000056|YES|HIGH|YES|NO|NO|N/A|NO|RECIPIENT_ONLY|the controller|shall notify|NONE_EXPLICIT|the supervisory authority competent under Article 55|N/A|VALIDATED_WITH_CONDITIONS|CONDITIONAL|The modal predicate and explicit authority recipient are absent from the fragment.
EXT-000092|YES|HIGH|NO|NO|NO|NO|NO|RECIPIENT_ONLY|The controller or processor|shall provide|NONE_EXPLICIT|the certification body referred to in Article 43|N/A|VALIDATED_WITH_CONDITIONS|CONDITIONAL|The source identifies a certification-body recipient; the row begins within a certification-mechanism phrase.
EXT-000205|PARTIALLY|HIGH|NO|YES|YES|N/A|N/A|NEITHER|NO_EXPLICIT_ACTOR|shall be informed|NONE_EXPLICIT|NONE_EXPLICIT|N/A|REQUIRES_MORE_REPRESENTATIVES|LOW|This is a passive information proposition; data subject should not be invented as actor.
EXT-000208|YES|LOW|NO|NO|NO|N/A|N/A|NEITHER|The Board|shall issue guidelines recommendations and best practices|NONE_EXPLICIT|NONE_EXPLICIT|N/A|HUMAN_REVIEW_REQUIRED|LOW|The row is a fragment of Article 70's enumerated Board powers.
EXT-000265|YES|HIGH|YES|YES|YES|NO|NO|NEITHER|Member States|may maintain or introduce|NONE_EXPLICIT|NONE_EXPLICIT|N/A|VALIDATED_WITH_CONDITIONS|CONDITIONAL|The purpose/processing phrase is not a relational actor.
EXT-000279|NO|HIGH|YES|YES|YES|N/A|N/A|NEITHER|The Commission|may recognise|NONE_EXPLICIT|NONE_EXPLICIT|N/A|REJECTED|NONE|The recital proposition is structurally preserved.
EXT-000294|YES|HIGH|YES|YES|YES|NO|NO|NEITHER|Each supervisory authority|should have|NONE_EXPLICIT|NONE_EXPLICIT|N/A|VALIDATED_WITH_CONDITIONS|CONDITIONAL|Financial resources are from the preceding provision proposition, not relational fields.
EXT-000341|PARTIALLY|HIGH|YES|NO|YES|NO|NO|COUNTERPART_ONLY|Every data subject|should have the right to lodge|a single supervisory authority|NONE_EXPLICIT|N/A|VALIDATED_WITH_CONDITIONS|CONDITIONAL|The entitlement construction is reduced; the supervisory authority is the direct complaint counterpart.
EXT-000369|YES|LOW|NO|NO|NO|NO|NO|UNCERTAIN|Member States law|should reconcile|NONE_EXPLICIT|NONE_EXPLICIT|N/A|HUMAN_REVIEW_REQUIRED|LOW|The extraction is a clause fragment and confuses the reconciliation proposition.
EXT-000490|NO|HIGH|YES|YES|YES|N/A|N/A|NEITHER|Providers of intermediary services|shall make public|NONE_EXPLICIT|NONE_EXPLICIT|N/A|REJECTED|NONE|The source proposition is retained.
EXT-000749|YES|LOW|NO|NO|NO|NO|NO|NEITHER|Member States|should provide|NONE_EXPLICIT|NONE_EXPLICIT|HUMAN_ADJUDICATION_REQUIRED|N/A|N/A|The row is imported from a different recital proposition on authority powers.
EXT-000852|YES|MEDIUM|NO|NO|NO|NO|NO|NEITHER|The monetisation via advertising revenue|can be restricted|NONE_EXPLICIT|NONE_EXPLICIT|HUMAN_ADJUDICATION_REQUIRED|N/A|N/A|The row loses the nominal subject and crosses separate restriction examples.
EXT-000589|NO|HIGH|YES|YES|YES|N/A|N/A|NEITHER|The Commission|shall support|NONE_EXPLICIT|NONE_EXPLICIT|N/A|REJECTED|NONE|The Article 44 update proposition is retained.
EXT-000486|PARTIALLY|HIGH|YES|YES|YES|NO|NO|NEITHER|Member States|shall ensure|NONE_EXPLICIT|NONE_EXPLICIT|N/A|REQUIRES_MORE_REPRESENTATIVES|LOW|The provider phrase is a transmission condition, not a relational role.
EXT-000496|YES|HIGH|YES|NO|YES|N/A|NO|RECIPIENT_ONLY|Providers of intermediary services|shall notify|NONE_EXPLICIT|the Digital Services Coordinator|N/A|VALIDATED_WITH_CONDITIONS|CONDITIONAL|The source legal verb is notify and the Coordinator is the explicit recipient.
EXT-000501|NO|HIGH|YES|YES|YES|N/A|N/A|NEITHER|Providers of intermediary services|shall make publicly available|NONE_EXPLICIT|NONE_EXPLICIT|N/A|REJECTED|NONE|The source proposition is preserved.
EXT-000632|PARTIALLY|HIGH|YES|YES|YES|NO|NO|RECIPIENT_ONLY|the Board|may refer|NONE_EXPLICIT|the Commission|HUMAN_ADJUDICATION_REQUIRED|N/A|N/A|The assessment phrase is contextual; the Commission is the direct referral recipient.
EXT-000715|NO|HIGH|YES|YES|YES|N/A|N/A|NEITHER|The Commission|shall draw up|NONE_EXPLICIT|NONE_EXPLICIT|N/A|REJECTED|NONE|The delegated-power report proposition is retained.
EXT-000746|YES|LOW|NO|NO|NO|NO|NO|UNCERTAIN|NO_EXPLICIT_ACTOR|cannot be subject|NONE_EXPLICIT|NONE_EXPLICIT|N/A|HUMAN_REVIEW_REQUIRED|LOW|The extraction begins in a limiting independence clause and needs full-recital anchoring.
EXT-000761|YES|MEDIUM|NO|NO|NO|NO|NO|NEITHER|The Commission and national competent authorities|should cooperate|NONE_EXPLICIT|NONE_EXPLICIT|N/A|HUMAN_REVIEW_REQUIRED|LOW|The row begins with a conjunction and imports a ne bis in idem condition.
EXT-000825|YES|HIGH|YES|NO|YES|N/A|NO|RECIPIENT_ONLY|The provider of intermediary services|should inform|NONE_EXPLICIT|the issuing authority|N/A|VALIDATED_WITH_CONDITIONS|CONDITIONAL|The legal predicate and issuing-authority recipient should be preserved.
EXT-000840|PARTIALLY|HIGH|YES|NO|YES|N/A|N/A|NEITHER|providers of very large online platforms|should pay due regard to|NONE_EXPLICIT|NONE_EXPLICIT|N/A|REQUIRES_MORE_REPRESENTATIVES|LOW|The source modal is lost but the core actor and object remain.
EXT-000930|NO|HIGH|YES|YES|YES|N/A|N/A|NEITHER|The Court of Justice of the European Union|shall have unlimited jurisdiction to review|NONE_EXPLICIT|NONE_EXPLICIT|N/A|REJECTED|NONE|The source proposition is retained.
EXT-001283|YES|LOW|NO|NO|NO|NO|NO|UNCERTAIN|The Commission|should be able to establish|NONE_EXPLICIT|NONE_EXPLICIT|HUMAN_ADJUDICATION_REQUIRED|N/A|N/A|The row mixes standardisation recital propositions and requires full anchor reconstruction.
EXT-000919|YES|HIGH|YES|YES|YES|NO|NO|RECIPIENT_ONLY|the notified body|shall refuse to issue and shall inform|NONE_EXPLICIT|the applicant|N/A|VALIDATED_WITH_CONDITIONS|CONDITIONAL|The applicant is the explicit recipient; another notified body is not the relation in this proposition.
EXT-000913|YES|HIGH|NO|YES|YES|NO|NO|NEITHER|NO_EXPLICIT_ACTOR|shall be granted full access|NONE_EXPLICIT|NONE_EXPLICIT|N/A|VALIDATED_WITH_CONDITIONS|CONDITIONAL|The notified body is passive beneficiary; copied relation is unsupported.
EXT-000916|YES|HIGH|YES|NO|NO|NO|NO|RECIPIENT_ONLY|the notified body|shall issue|NONE_EXPLICIT|the applicant|N/A|VALIDATED_WITH_CONDITIONS|CONDITIONAL|The certificate-issue proposition has a distinct applicant recipient and should not use another notified body.
EXT-000944|YES|LOW|NO|NO|NO|N/A|N/A|UNCERTAIN|NO_EXPLICIT_ACTOR|SOURCE_ANCHORED_RECONSTRUCTION_REQUIRED|NONE_EXPLICIT|NONE_EXPLICIT|HUMAN_ADJUDICATION_REQUIRED|N/A|N/A|The extracted fragment lacks enough local source wording to fix a proposition without full Article 112 reconstruction.
'@ -split "`r?`n"|Where-Object {$_};$d=@{};foreach($l in $data){$p=$l-split '\|',17;if($p.Count-ne 17){throw "bad $l"};$d[$p[0]]=$p};if($d.Count-ne 36){throw 'decision count'}
$now=Get-Date -Format 'yyyy-MM-ddTHH:mm:ssK';$out=foreach($r in $input){$p=$d[$r.RECORD_ID];[pscustomobject][ordered]@{CASE_ID=$r.CASE_ID;RECORD_ID=$r.RECORD_ID;BATCH_ID='B1-02';REVIEW_TYPE=$r.REVIEW_SCOPE;SOURCE_TYPE=$r.SOURCE_TYPE;SOURCE_REFERENCE=$r.SOURCE_REFERENCE;INPUT_HASH=$r.INPUT_HASH;MODEL_REQUESTED='GPT-5.6 Terra High';MODEL_RESEARCHER_SELECTED='GPT-5.6 Terra High';MODEL_RUNTIME_VARIANT='MODEL_VARIANT_NOT_EXPOSED';RUN_TIMESTAMP=$now;ADVANCED_DEFECT_PRESENT=$p[1];PROPOSITION_ANCHOR_CONFIDENCE=$p[2];ACTOR_CORRECT=$p[3];ACTION_CORRECT=$p[4];OBJECT_CORRECT=$p[5];COUNTERPART_CORRECT=$p[6];RECIPIENT_CORRECT=$p[7];PROPOSED_ACTOR=$p[9];PROPOSED_ACTION=$p[10];PROPOSED_OBJECT=if($p[5]-eq 'NO'){'SOURCE_ANCHORED_RECONSTRUCTION_REQUIRED'}else{$r.ORIGINAL_OBJECT};PROPOSED_COUNTERPART=$p[11];PROPOSED_RECIPIENT=$p[12];PROPOSED_CONTEXT_MODIFIER='SEE_ADVANCED_REASONING_NOTE';RELATIONAL_FIELD_DIFFERENTIATION=$p[8];RELATIONAL_ENTITY=if($p[8]-eq 'RECIPIENT_ONLY'){$p[12]}elseif($p[8]-eq 'COUNTERPART_ONLY'){$p[11]}else{'NONE_EXPLICIT'};RELATIONAL_ROLE_RATIONALE=$p[16];ADVANCED_REASONING_NOTE=$p[16];TEMPLATE_GENERALIZABILITY=$p[15];FAMILY_TEMPLATE_STATUS=$p[14];REPAIR_TEMPLATE=if($p[14]-eq 'VALIDATED_WITH_CONDITIONS'){'Apply only when source anchor and exact matrix legal predicate match.'}else{''};TEMPLATE_APPLICATION_CONDITIONS=if($p[14]-eq 'VALIDATED_WITH_CONDITIONS'){'Verify source wording and prohibit cross-proposition application.'}else{''};CASE_ROUTE_AFTER_REVIEW=$p[13]}}
$out|Export-Csv (Join-Path $b 'R4_2E_B1_ADVANCED_VALIDATION_B1_02.csv') -NoTypeInformation -Encoding utf8;$hash=(Get-FileHash (Join-Path $b 'R4_2E_B1_ADVANCED_VALIDATION_B1_02.csv') -Algorithm SHA256).Hash;"rows=$($out.Count);hash=$hash"
