$ErrorActionPreference='Stop'
$r4=Split-Path -Parent $PSScriptRoot;$root=Join-Path $r4 '03_extraction';$b1=Join-Path $root 'qa\repair\R4_2E_B1'
$input=@(Import-Csv (Join-Path $b1 'R4_2E_B1_BLIND_SUBSTANTIVE_REVIEW_INPUT.csv') -Encoding UTF8|Where-Object BATCH_ID -eq 'B1-01'|Sort-Object ORDER_IN_BATCH)
$manifest=@(Import-Csv (Join-Path $b1 'R4_2E_B1_BATCH_MANIFEST.csv') -Encoding UTF8)
if($input.Count -ne 36){throw 'B1-01 is not 36 records.'}

# Each line: ID;defect;confidence;actor;action;object;counterpart;recipient;relation;proposed actor;proposed action;proposed object;proposed counterpart;proposed recipient;context;note;template generalizability;template status;individual route
$lines=@'
EXT-000150;YES;HIGH;NO;NO;NO;N/A;N/A;NEITHER;Each Member State;may provide by law;that its supervisory authority shall have additional powers referred to in paragraphs 1, 2 and 3;NONE_EXPLICIT;NONE_EXPLICIT;The exercise of those powers shall not impair Chapter VII;The extraction anchors an embedded supervisory-authority clause instead of the matrix proposition.;N/A;N/A;HUMAN_ADJUDICATION_REQUIRED
EXT-000357;YES;HIGH;NO;NO;NO;N/A;N/A;NEITHER;The controller or processor;should compensate;any damage which a person may suffer as a result of processing that infringes this Regulation;NONE_EXPLICIT;NONE_EXPLICIT;;The extraction promotes the embedded suffer predicate and its person phrase over the compensation proposition.;N/A;N/A;HUMAN_ADJUDICATION_REQUIRED
EXT-000386;YES;MEDIUM;NO;NO;NO;NO;NO;NEITHER;Personal data which have undergone pseudonymisation;should be considered;information on an identifiable natural person;NONE_EXPLICIT;NONE_EXPLICIT;To determine identifiability, account should be taken of reasonably likely means;The row combines a subordinate attribution phrase with the later pseudonymisation proposition.;N/A;N/A;HUMAN_ADJUDICATION_REQUIRED
EXT-000085;YES;HIGH;YES;NO;NO;NO;NO;NEITHER;The supervisory authority;shall provide an opinion and shall approve;whether the draft code, amendment or extension complies with this Regulation;NONE_EXPLICIT;NONE_EXPLICIT;;The generic action and relational phrase import material from the preceding submission proposition.;N/A;N/A;N/A
EXT-000013;YES;HIGH;YES;NO;YES;NO;NO;RECIPIENT_ONLY;the controller;shall provide;the data subject with information on the other purpose and relevant paragraph 2 information;NONE_EXPLICIT;the data subject;prior to that further processing;The recipient is omitted and an informational modifier is incorrectly treated as a relational entity.;CONDITIONAL;VALIDATED_WITH_CONDITIONS;N/A
EXT-000027;PARTIALLY;HIGH;YES;NO;YES;UNCERTAIN;UNCERTAIN;UNCERTAIN;the data subject;shall have the right to have transmitted;personal data directly from one controller to another;UNCERTAIN;UNCERTAIN;;The right/deontic construction is incomplete, and the two controllers require proposition-specific relational treatment.;CONDITIONAL;REQUIRES_MORE_REPRESENTATIVES;N/A
EXT-000035;YES;HIGH;NO;YES;YES;NO;NO;NEITHER;Union or Member State law to which the controller or processor is subject;may restrict by a legislative measure;the scope of listed obligations and rights;NONE_EXPLICIT;NONE_EXPLICIT;when the stated safeguards and necessity/proportionality conditions are met;The original actor is truncated and the prepositional rights phrase is not a relational actor.;CONDITIONAL;VALIDATED_WITH_CONDITIONS;N/A
EXT-000068;YES;HIGH;YES;NO;N/A;NO;NO;COUNTERPART_ONLY;The controller;shall consult;NONE_EXPLICIT;the supervisory authority;NONE_EXPLICIT;prior to processing;Consult or hear paraphrases the source and the directly consulted authority was dropped.;CONDITIONAL;VALIDATED_WITH_CONDITIONS;N/A
EXT-000192;YES;HIGH;YES;NO;NO;NO;NO;RECIPIENT_ONLY;The Chair of the Board;shall notify;the decision referred to in paragraph 1;NONE_EXPLICIT;the supervisory authorities concerned;without undue delay;The row fuses notification, Commission information and publication, so it should anchor the first notification proposition.;LOW;REQUIRES_MORE_REPRESENTATIVES;N/A
EXT-000206;PARTIALLY;HIGH;YES;NO;YES;N/A;N/A;NEITHER;The data subject;shall have the right to withdraw;his or her consent;NONE_EXPLICIT;NONE_EXPLICIT;at any time;The core proposition is present but the legal right construction is reduced to a bare withdrawal action.;CONDITIONAL;VALIDATED_WITH_CONDITIONS;N/A
EXT-000220;YES;HIGH;YES;YES;YES;NO;NO;NEITHER;every data subject;shall have the right to lodge;complaint with a supervisory authority;NONE_EXPLICIT;NONE_EXPLICIT;without prejudice to any other administrative or judicial remedy;The remedy phrase is a limiting context, not a counterpart or recipient.;CONDITIONAL;VALIDATED_WITH_CONDITIONS;N/A
EXT-000221;YES;HIGH;YES;NO;YES;N/A;NO;RECIPIENT_ONLY;The supervisory authority with which the complaint has been lodged;shall inform;the complainant on progress and outcome of the complaint including the possibility of a judicial remedy;NONE_EXPLICIT;the complainant;;The action is paraphrased and the explicit recipient is absent.;CONDITIONAL;VALIDATED_WITH_CONDITIONS;N/A
EXT-000270;YES;HIGH;YES;NO;NO;NO;NO;NEITHER;The Commission;may decide to revoke;an adequacy decision;NONE_EXPLICIT;NONE_EXPLICIT;having given notice and a full statement of reasons to the third country or international organisation;Also is not the predicate, and the notice recipient is not the relational role of the revoke proposition.;CONDITIONAL;VALIDATED_WITH_CONDITIONS;N/A
EXT-000273;YES;HIGH;YES;NO;NO;NO;NO;NEITHER;The Commission;should take account of;obligations arising from participation in multilateral or regional systems and their implementation;NONE_EXPLICIT;NONE_EXPLICIT;Apart from the stated international commitments;Consult or hear is not the source predicate and the from phrase is not a recipient.;CONDITIONAL;VALIDATED_WITH_CONDITIONS;N/A
EXT-000277;YES;HIGH;YES;NO;NO;NO;NO;NEITHER;the Commission;should provide for;periodic review mechanism of adequacy decisions;NONE_EXPLICIT;NONE_EXPLICIT;The review should be conducted in consultation with the third country or international organisation;The row maps an embedded object phrase as a generic information action and duplicates a consultation modifier in relational fields.;LOW;REQUIRES_MORE_REPRESENTATIVES;N/A
EXT-000290;PARTIALLY;HIGH;YES;YES;YES;NO;NO;NEITHER;Member States;should be able to establish;more than one supervisory authority;NONE_EXPLICIT;NONE_EXPLICIT;to reflect their constitutional, organisational and administrative structure;The matrix proposition is preserved, but a purpose clause was copied into both relational fields.;CONDITIONAL;VALIDATED_WITH_CONDITIONS;N/A
EXT-000346;YES;MEDIUM;NO;NO;NO;NO;NO;NEITHER;Member States;should provide that bodies, organisations or associations may lodge;complaints independently of a data subject's mandate;NONE_EXPLICIT;NONE_EXPLICIT;in accordance with Member State law;The extraction begins within an embedded entitlement and loses the matrix legislative proposition.;LOW;HUMAN_REVIEW_REQUIRED;N/A
EXT-000478;YES;LOW;NO;NO;NO;NO;NO;UNCERTAIN;NO_EXPLICIT_ACTOR;should be without prejudice to;intervention of the supervisory authority;NONE_EXPLICIT;NONE_EXPLICIT;where the controller has consulted and no reaction occurred within the relevant period;The row is a proposition fragment whose actor and relational fields come from distinct contextual clauses.;NONE;HUMAN_REVIEW_REQUIRED;N/A
EXT-000487;YES;HIGH;YES;YES;NO;NO;NO;RECIPIENT_ONLY;providers of intermediary services;shall inform;the recipient of the service of the order received and effect given to it;NONE_EXPLICIT;the recipient of the service;at the latest when effect is given to the order;The order is content, not recipient, and the source identifies the recipient of the service.;N/A;N/A;MODEL_REPAIR_PROPOSAL_ACCEPTABLE_FOR_HUMAN_QA
EXT-000811;YES;MEDIUM;NO;NO;NO;N/A;N/A;NEITHER;The rules on liability of providers of intermediary services;should establish;when the provider concerned cannot be held liable in relation to illegal content;NONE_EXPLICIT;NONE_EXPLICIT;Union or national law determines positive liability;The source is a recital clarification, not a proposition in which a basis phrase performs the predicate.;N/A;N/A;HUMAN_ADJUDICATION_REQUIRED
EXT-000529;NO;HIGH;YES;YES;YES;N/A;N/A;NEITHER;The Commission;shall publish and keep up to date;the paragraph 4 information in a publicly available database;NONE_EXPLICIT;NONE_EXPLICIT;in an easily accessible and machine-readable format;The source anchor, actor, coordinated predicate and object are structurally preserved.;N/A;N/A;N/A
EXT-000498;YES;HIGH;YES;NO;YES;NO;NO;RECIPIENT_ONLY;Providers of intermediary services;shall inform;recipients of the service of significant changes to terms and conditions;NONE_EXPLICIT;recipients of the service;;The terms and conditions are content, and the recipient is the recipient of the service.;CONDITIONAL;VALIDATED_WITH_CONDITIONS;N/A
EXT-000503;NO;HIGH;YES;YES;YES;N/A;N/A;NEITHER;Providers of hosting services;shall put mechanisms in place;to allow any individual or entity to notify them of illegal content;NONE_EXPLICIT;NONE_EXPLICIT;;The source predicate and governed mechanism content are retained, and no relational value is required for this row.;NONE;REJECTED;N/A
EXT-000511;YES;HIGH;YES;NO;NO;NO;NO;RECIPIENT_ONLY;Providers of online platforms;shall provide;recipients of the service, including notice submitters, with access to an effective internal complaint-handling system;NONE_EXPLICIT;recipients of the service, including individuals or entities that submitted a notice;for at least six months after the decision;A relational phrase naming a system is not an actor, while the source has explicit recipients and a bounded access entitlement.;LOW;REQUIRES_MORE_REPRESENTATIVES;N/A
EXT-000515;NO;HIGH;YES;YES;YES;N/A;N/A;NEITHER;Providers of online platforms;shall ensure;that paragraph 5 decisions are taken under qualified-staff supervision and not solely by automated means;NONE_EXPLICIT;NONE_EXPLICIT;;The proposition remains intact, and staff supervision is an object condition rather than a relational actor.;NONE;REJECTED;N/A
EXT-000588;YES;HIGH;YES;NO;NO;N/A;NO;COUNTERPART_ONLY;The Commission;shall consult;the Board;the Board;NONE_EXPLICIT;and shall support and promote standards development;The source uses consult, not a synonym, and explicitly names the consulted body, while coordinated standards duties are separate.;CONDITIONAL;VALIDATED_WITH_CONDITIONS;N/A
EXT-000748;YES;HIGH;YES;NO;NO;NO;NO;NEITHER;Member States;should provide;the Digital Services Coordinator and other competent authorities with sufficient powers and means;NONE_EXPLICIT;NONE_EXPLICIT;to ensure effective investigation and enforcement;The generic information action and with phrase obscure the actual provision of powers and means.;CONDITIONAL;VALIDATED_WITH_CONDITIONS;N/A
EXT-000757;YES;MEDIUM;NO;NO;NO;NO;NO;NEITHER;Member States;should confer;supervisory and enforcement powers on competent authorities;NONE_EXPLICIT;NONE_EXPLICIT;including the competence of the Member State where a provider appointed its legal representative;The extraction treats an embedded competence clause as the main proposition, while full recital context supports a matrix allocation of powers.;LOW;HUMAN_REVIEW_REQUIRED;N/A
EXT-000758;PARTIALLY;HIGH;YES;YES;YES;NO;NO;NEITHER;The Commission;should be responsible;for supervision and enforcement in respect of very large online platforms and search engines;NONE_EXPLICIT;NONE_EXPLICIT;with support of national competent authorities where relevant;Support is a contextual means, not a counterpart/recipient, while the core responsibility predicate remains intact.;CONDITIONAL;VALIDATED_WITH_CONDITIONS;N/A
EXT-000841;YES;HIGH;NO;NO;NO;NO;NO;RECIPIENT_ONLY;providers of very large online platforms and very large online search engines;should also provide;recipients of the services with a concise and easily readable summary of main terms-and-conditions elements;NONE_EXPLICIT;recipients of the services;in all Member State official languages where services are offered;The row begins in a preceding language clause and uses also as the action, so it omits the actual provider actor and recipient.;LOW;REQUIRES_MORE_REPRESENTATIVES;N/A
EXT-001029;YES;HIGH;YES;NO;NO;NO;NO;COUNTERPART_ONLY;the Commission;shall consult;the advisory forum referred to in Article 67;the advisory forum referred to in Article 67;NONE_EXPLICIT;When drafting common specifications;The source predicate is consult, and the examination procedure belongs to a separate implementing-act proposition.;N/A;N/A;MODEL_REPAIR_PROPOSAL_ACCEPTABLE_FOR_HUMAN_QA
EXT-001348;YES;HIGH;NO;NO;NO;NO;NO;NEITHER;Compliance with obligations on providers of general-purpose AI models;should be enforceable;inter alia by means of fines;NONE_EXPLICIT;NONE_EXPLICIT;including failures to comply with Commission-requested measures;The initial obligation phrase is not an actor, and the relational field repeats an object-level compliance phrase.;N/A;N/A;HUMAN_ADJUDICATION_REQUIRED
EXT-001381;PARTIALLY;MEDIUM;NO;NO;NO;NO;NO;NEITHER;The use of AI tools by law enforcement and other relevant authorities;should not become;a factor of inequality, or exclusion;NONE_EXPLICIT;NONE_EXPLICIT;The impact on defence rights should not be ignored;The source subject is a nominal use phrase, while the extraction fragments it and imports a separate rights proposition.;N/A;N/A;HUMAN_ADJUDICATION_REQUIRED
EXT-000947;NO;HIGH;YES;YES;YES;N/A;N/A;NEITHER;Providers of high-risk AI systems;shall put;a quality management system in place that ensures compliance with this Regulation;NONE_EXPLICIT;NONE_EXPLICIT;;The actor, mandatory predicate and governed system are preserved, while subsequent documentation is a separate proposition.;N/A;N/A;N/A
EXT-000925;NO;HIGH;YES;YES;YES;N/A;N/A;NEITHER;the Commission;shall take into account;the Annex XIII criteria;NONE_EXPLICIT;NONE_EXPLICIT;for systemic-risk designation;The source anchor and structural slots are preserved, and enumerated criteria belong to the object.;NONE;REJECTED;N/A
EXT-000926;PARTIALLY;HIGH;YES;YES;YES;NO;NO;NEITHER;providers of high-risk AI systems;may exceptionally process;special categories of personal data;NONE_EXPLICIT;NONE_EXPLICIT;to the extent strictly necessary for bias detection and correction;The conditional necessity phrase is not an actor-capable counterpart/recipient, while the core exception is otherwise retained.;CONDITIONAL;VALIDATED_WITH_CONDITIONS;N/A
'@ -split "`r?`n" | Where-Object {$_}
$decision=@{};$validGeneralizability=@('HIGH','CONDITIONAL','LOW','NONE','N/A');$validTemplateStatus=@('VALIDATED','VALIDATED_WITH_CONDITIONS','REJECTED','REQUIRES_MORE_REPRESENTATIVES','HUMAN_REVIEW_REQUIRED','N/A');$validIndividualRoute=@('MODEL_REPAIR_PROPOSAL_ACCEPTABLE_FOR_HUMAN_QA','HUMAN_ADJUDICATION_REQUIRED','NO_REPAIR','ABSTAIN','N/A')
foreach($line in $lines){$p=$line -split ';',19;if($p.Count -ne 19){throw "Malformed decision: $line"};if($p[16] -notin $validGeneralizability -or $p[17] -notin $validTemplateStatus -or $p[18] -notin $validIndividualRoute){throw "Schema-invalid decision: $($p[0])"};$decision[$p[0]]=$p}
if($decision.Count -ne 36){throw "Expected 36 decisions; found $($decision.Count)."}
$now=(Get-Date -Format 'yyyy-MM-ddTHH:mm:ssK');$out=[System.Collections.Generic.List[object]]::new()
foreach($r in $input){$p=$decision[$r.RECORD_ID];if(-not $p){throw "No decision for $($r.RECORD_ID)"};$out.Add([pscustomobject][ordered]@{CASE_ID=$r.CASE_ID;RECORD_ID=$r.RECORD_ID;BATCH_ID=$r.BATCH_ID;REVIEW_TYPE=$r.REVIEW_SCOPE;SOURCE_TYPE=$r.SOURCE_TYPE;SOURCE_REFERENCE=$r.SOURCE_REFERENCE;INPUT_HASH=$r.INPUT_HASH;MODEL_REQUESTED='GPT-5.6 Terra High';MODEL_RESEARCHER_SELECTED='GPT-5.6 Terra High';MODEL_RUNTIME_VARIANT='MODEL_VARIANT_NOT_EXPOSED';RUN_TIMESTAMP=$now;ADVANCED_DEFECT_PRESENT=$p[1];PROPOSITION_ANCHOR_CONFIDENCE=$p[2];ACTOR_CORRECT=$p[3];ACTION_CORRECT=$p[4];OBJECT_CORRECT=$p[5];COUNTERPART_CORRECT=$p[6];RECIPIENT_CORRECT=$p[7];PROPOSED_ACTOR=$p[9];PROPOSED_ACTION=$p[10];PROPOSED_OBJECT=$p[11];PROPOSED_COUNTERPART=$p[12];PROPOSED_RECIPIENT=$p[13];PROPOSED_CONTEXT_MODIFIER=$p[14];RELATIONAL_FIELD_DIFFERENTIATION=$p[8];RELATIONAL_ENTITY=if($p[8] -in @('COUNTERPART_ONLY','RECIPIENT_ONLY')){if($p[12] -ne 'NONE_EXPLICIT'){$p[12]}else{$p[13]}}else{'NONE_EXPLICIT'};RELATIONAL_ROLE_RATIONALE=$p[15];ADVANCED_REASONING_NOTE=$p[15];TEMPLATE_GENERALIZABILITY=$p[16];FAMILY_TEMPLATE_STATUS=$p[17];REPAIR_TEMPLATE=if($p[17] -eq 'VALIDATED_WITH_CONDITIONS'){'Apply only where the frozen source has the stated matrix predicate and the existing field demonstrably substitutes it, promotes a non-actor prepositional phrase, or drops an explicit addressee.'}else{''};TEMPLATE_APPLICATION_CONDITIONS=if($p[17] -eq 'VALIDATED_WITH_CONDITIONS'){'Verify the same proposition anchor, source wording, clause structure and relational role for every candidate; do not apply across coordinated or embedded propositions.'}else{''};CASE_ROUTE_AFTER_REVIEW=$p[18]})}
$out|Export-Csv (Join-Path $b1 'R4_2E_B1_ADVANCED_VALIDATION.csv') -NoTypeInformation -Encoding UTF8
$templates=[System.Collections.Generic.List[object]]::new();$individuals=[System.Collections.Generic.List[object]]::new()
foreach($o in $out){$manifestRow=$manifest|Where-Object RECORD_ID -eq $o.RECORD_ID|Select-Object -First 1;if($manifestRow.REVIEW_TYPE -eq 'TEMPLATE_REPRESENTATIVE'){[void]$templates.Add($o)}elseif($manifestRow.REVIEW_TYPE -eq 'INDIVIDUAL_ADVANCED_CASE'){[void]$individuals.Add($o)}}
$templates|Select-Object CASE_ID,RECORD_ID,BATCH_ID,SOURCE_REFERENCE,ADVANCED_DEFECT_PRESENT,PROPOSITION_ANCHOR_CONFIDENCE,TEMPLATE_GENERALIZABILITY,FAMILY_TEMPLATE_STATUS,REPAIR_TEMPLATE,TEMPLATE_APPLICATION_CONDITIONS,ADVANCED_REASONING_NOTE|Export-Csv (Join-Path $b1 'R4_2E_B1_FAMILY_TEMPLATE_VALIDATION.csv') -NoTypeInformation -Encoding UTF8
$individuals|Export-Csv (Join-Path $b1 'R4_2E_B1_INDIVIDUAL_CASE_DECISIONS.csv') -NoTypeInformation -Encoding UTF8
$out|Select-Object CASE_ID,RECORD_ID,BATCH_ID,RELATIONAL_FIELD_DIFFERENTIATION,RELATIONAL_ENTITY,RELATIONAL_ROLE_RATIONALE,ADVANCED_DEFECT_PRESENT|Export-Csv (Join-Path $b1 'R4_2E_B1_RELATIONAL_FIELD_DIFFERENTIATION.csv') -NoTypeInformation -Encoding UTF8
$outputHash=(Get-FileHash (Join-Path $b1 'R4_2E_B1_ADVANCED_VALIDATION.csv') -Algorithm SHA256).Hash
$log=@(Import-Csv (Join-Path $b1 'R4_2E_B1_BATCH_RUN_LOG.csv') -Encoding UTF8);foreach($x in $log){if($x.BATCH_ID -eq 'B1-01'){$x.RUN_VERSION='v2_SCHEMA_CORRECTED';$x.OUTPUT_HASH=$outputHash;$x.END_STATUS='R4_2E_B1_BATCH_01_COMPLETE_PENDING_CONTROL_UNBLINDING';$x.COMPLETION_STATUS='COMPLETE';$x.RUN_TIMESTAMP=$now}};$log|Export-Csv (Join-Path $b1 'R4_2E_B1_BATCH_RUN_LOG.csv') -NoTypeInformation -Encoding UTF8
"Batch B1-01 complete: rows=$($out.Count); templates=$($templates.Count); individual=$($individuals.Count); hash=$outputHash"
